on: workflow_dispatch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myacr4568975.azurecr.io
        username: ${{ secrets.acr_myacr4568975_username }}
        password: ${{ secrets.acr_myacr4568975_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t myacr4568975.azurecr.io/devopsclusteraks:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push myacr4568975.azurecr.io/devopsclusteraks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_devopsclusteraks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep workflownamespacetest | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace workflownamespacetest`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: workflownamespacetest
        container-registry-url: myacr4568975.azurecr.io
        container-registry-username: ${{ secrets.acr_myacr4568975_username }}
        container-registry-password: ${{ secrets.acr_myacr4568975_password }}
        secret-name: devopsclustedockerauth
       
    - uses: azure/k8s-deploy@v3.1
      with:
        namespace: workflownamespacetest
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          myacr4568975.azurecr.io/devopsclusteraks:${{ github.sha }}
        imagepullsecrets: |
          devopsclustedockerauth
        force: true
